import { useMemo, useState } from 'react'
import { AlertOctagon, Calculator, RotateCcw, ShieldCheck } from 'lucide-react'
import { Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { PageHeader, Panel } from '../components/Ui'
import { money, number, positionSize } from '../utils'

export default function RiskLab() {
  const [balance, setBalance] = useState(10000); const [risk, setRisk] = useState(1); const [entry, setEntry] = useState(118420); const [stop, setStop] = useState(117260); const [target, setTarget] = useState(121320); const [leverage, setLeverage] = useState(3); const [trades, setTrades] = useState(20); const [winRate, setWinRate] = useState(55); const [mode, setMode] = useState<'fixed' | 'compound'>('compound')
  const validPlan = balance > 0 && risk > 0 && risk <= 10 && entry > 0 && stop > 0 && target > 0 && entry !== stop && leverage >= 1
  const quantity = validPlan ? positionSize(balance, risk, entry, stop) : 0; const riskAmount = balance > 0 && risk > 0 ? balance * Math.min(risk, 10) / 100 : 0; const notional = quantity * entry; const margin = leverage >= 1 ? notional / leverage : 0; const reward = quantity * Math.abs(target - entry); const rr = riskAmount ? reward / riskAmount : 0
  const simulation = useMemo(() => { let account = Math.max(0, balance); const rows = [{ trade: 0, balance: account }]; const count = Math.min(100, Math.max(0, trades)); for (let i = 1; i <= count; i++) { const amount = (mode === 'compound' ? account : Math.max(0, balance)) * Math.min(10, Math.max(0, risk)) / 100; const winsByNow = Math.round(i * winRate / 100); const previousWins = Math.round((i - 1) * winRate / 100); account += winsByNow > previousWins ? amount * rr : -amount; rows.push({ trade: i, balance: Math.max(0, account) }) } return rows }, [balance, mode, risk, rr, trades, winRate])
  return <div className="page risk-page"><PageHeader eyebrow="Pre-trade discipline" title="Risk Lab" description="Size the loss first. The upside only matters after the account can survive the downside." actions={<button className="btn secondary" onClick={() => { setBalance(10000); setRisk(1); setEntry(118420); setStop(117260); setTarget(121320) }}><RotateCcw size={16} /> Reset</button>} />
    <div className="risk-layout"><Panel title="Trade calculator" meta={<Calculator size={18} />} className="risk-form"><div className="form-grid"><label>Account balance<div className="input-prefix"><span>$</span><input type="number" value={balance} onChange={(e) => setBalance(Number(e.target.value))} /></div></label><label>Risk per trade<div className="input-prefix suffix"><input type="number" step=".1" value={risk} onChange={(e) => setRisk(Number(e.target.value))} /><span>%</span></div></label><label>Entry price<input type="number" value={entry} onChange={(e) => setEntry(Number(e.target.value))} /></label><label>Stop loss<input type="number" value={stop} onChange={(e) => setStop(Number(e.target.value))} /></label><label>Primary target<input type="number" value={target} onChange={(e) => setTarget(Number(e.target.value))} /></label><label>Leverage<input type="number" min="1" value={leverage} onChange={(e) => setLeverage(Number(e.target.value))} /></label></div><div className="risk-warning"><AlertOctagon size={17} /><span>Maximum planned loss</span><strong>{money(riskAmount)}</strong></div></Panel>
      <Panel title="Position plan" className="position-output"><div className="output-primary"><span>POSITION QUANTITY</span><strong>{number(quantity, 5)}</strong><small>{validPlan ? `≈ ${money(notional)}` : 'Enter a valid plan'}</small></div><div className="output-grid"><div><span>Margin required</span><strong>{money(margin)}</strong></div><div><span>Possible profit</span><strong className="text-positive">{money(reward)}</strong></div><div><span>Possible loss</span><strong className="text-negative">-{money(riskAmount)}</strong></div><div><span>Reward / risk</span><strong>{rr.toFixed(2)}R</strong></div><div><span>Stop distance</span><strong>{entry > 0 ? (Math.abs(entry - stop) / entry * 100).toFixed(2) : 0}%</strong></div><div><span>Exposure</span><strong>{balance > 0 ? (notional / balance * 100).toFixed(0) : 0}%</strong></div></div><div className="safety-callout"><ShieldCheck size={18} /><p><strong>{!validPlan ? 'Complete a valid trade plan.' : risk <= 1 ? 'Plan is inside the 1% guardrail.' : `Plan risks ${risk.toFixed(1)}% of the account.`}</strong><span>Leverage changes margin, not the dollar risk defined by your stop.</span></p></div></Panel>
      <Panel title="Trade sequence simulator" meta={<div className="segmented small"><button className={mode === 'fixed' ? 'active' : ''} onClick={() => setMode('fixed')}>Fixed</button><button className={mode === 'compound' ? 'active' : ''} onClick={() => setMode('compound')}>Compound</button></div>} className="simulator-panel"><div className="simulation-controls"><label>Trades <input type="number" min="5" max="100" value={trades} onChange={(e) => setTrades(Number(e.target.value))} /></label><label>Win rate <input type="range" min="20" max="80" value={winRate} onChange={(e) => setWinRate(Number(e.target.value))} /><strong>{winRate}%</strong></label><div><span>Projected balance</span><strong>{money(simulation.at(-1)?.balance ?? balance)}</strong></div></div><div className="simulation-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={simulation}><XAxis dataKey="trade" hide /><YAxis hide domain={['dataMin - 100', 'dataMax + 100']} /><Tooltip contentStyle={{ background: '#101820', border: '1px solid #2a3740' }} formatter={(value) => money(Number(value))} /><Line type="monotone" dataKey="balance" stroke="#f6c453" strokeWidth={2} dot={false} /></LineChart></ResponsiveContainer></div></Panel>
    </div>
  </div>
}
